### ISSUE TITLE
psweb crash

### ISSUE THREAD

**Issue by asoltys** [Impa10r/peerswap-web#95]
Running psweb v1.7.4 as a plugin for CLN 24.11.1 it seemed to work fine for a few minutes. I came back to look at it again hours later and found it had crashed:

```
2024/12/19 22:44:38 Polled peers for balances
fatal error: concurrent map read and map write

goroutine 661604 [running]:
peerswap-web/cmd/psweb/ln.CacheHTLCs({0xc0169be7d0, 0x50})
        /peerswap-web/cmd/psweb/ln/cln.go:521 +0x9a9
main.onSendPaySuccess.func1({0xc00511a280, 0x40})
        /peerswap-web/cmd/psweb/main-cln.go:111 +0x56
created by main.onSendPaySuccess in goroutine 661815
        /peerswap-web/cmd/psweb/main-cln.go:109 +0x70

goroutine 1 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc00c452000, 0x800)
        /usr/local/go/src/syscall/syscall_linux.go:73 +0x25
syscall.read(0xc000054120?, {0xc00c452000?, 0xc000512bc0?, 0x419f05?})
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:736 +0x38
syscall.Read(...)
        /usr/local/go/src/syscall/syscall_unix.go:183
internal/poll.ignoringEINTRIO(...)
        /usr/local/go/src/internal/poll/fd_unix.go:745
internal/poll.(*FD).Read(0xc000054120, {0xc00c452000, 0x800, 0x800})
        /usr/local/go/src/internal/poll/fd_unix.go:161 +0x2ae
os.(*File).read(...)
        /usr/local/go/src/os/file_posix.go:29
os.(*File).Read(0xc00007a058, {0xc00c452000?, 0xc000512c38?, 0xc0000fe9c0?})
        /usr/local/go/src/os/file.go:124 +0x52
bufio.(*Scanner).Scan(0xc000512d40)
        /usr/local/go/src/bufio/scan.go:219 +0x81e
github.com/elementsproject/glightning/jrpc2.(*Server).listen(0xc00002a0f0, {0x168a040?, 0xc00007a058?})
        /root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20240910115322-5c07410a8494/jrpc2/server.go:108 +0xfe
github.com/elementsproject/glightning/jrpc2.(*Server).StartUp(0xc00002a0f0, 0xc00007a058, 0xc00007a060)
        /root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20240910115322-5c07410a8494/jrpc2/server.go:69 +0x92
github.com/elementsproject/glightning/glightning.(*Plugin).Start(0xc000318000, 0xc00007a058, 0xc00007a060)
        /root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20240910115322-5c07410a8494/glightning/plugin.go:1294 +0x13e
main.main()
        /peerswap-web/cmd/psweb/main-cln.go:73 +0x3b8

```

**Comment by Impa10r** [comment]
thanks, will investigate

**Comment by Impa10r** [comment]
@asoltys Hi Adam. Thanks for catching this bug! Could you try building v1.7.5 and see if it runs fine? You can do that with:

```
rm -rf peerswap-web && \
git clone -b v1.7.5 https://github.com/Impa10r/peerswap-web && \
cd peerswap-web && \
make -j$(nproc) install-cln && \
lightning-cli -k plugin subcommand=stop plugin=${HOME}/go/bin/psweb && \
lightning-cli -k plugin subcommand=start plugin=${HOME}/go/bin/psweb
```

I only run a small CLN testnet node and don't know anyone else who uses PSWeb with CLN in production. Thanks a lot!

**Comment by asoltys** [comment]
Hey sorry it took me a while but I've had it running on 1.7.5 for a few hours now today and so far so good!
